---
ID: "c47eb1e8-9d66-47ca-8b68-93704d261b1a"
Parent: "dcab1d53-e94b-45e1-bdcf-650581c1c5bc"
Template: "dcab1d53-e94b-45e1-bdcf-650581c1c5bc"
Path: /sitecore/templates/Project/ClothingCompany/Content Items/Author Details/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210527T152622Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
