---
ID: "7a022894-98e5-429c-aa6b-7a3c82e9cafb"
Parent: "df85e3d3-05f5-4bfa-b64a-f48f0c55ba52"
Template: "df85e3d3-05f5-4bfa-b64a-f48f0c55ba52"
Path: /sitecore/templates/Feature/BasicContent/_Banner/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200304T140555Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
